---

owner: ravngr
repo: status

sites:
  - name: Electric Toast (IPv4)
    url: https://ipv4.etoast.net/ping
  - name: Electric Toast (IPv6)
    url: https://ipv6.etoast.net/ping

status-website:
  cname: status.etoast.net
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Toast Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
